"""
List all the application graphs to be used for evaluation.
"""

hotel_reservation = {
    "services": [
        "frontend",
        "search",
        "reservation",
        "user",
        "recommendation",
        "profile",
        "geo",
        "rate",
        "memcached-profile",
        "memcached-rate",
        "memcached-reserve",
        "mongodb-geo",
        "mongodb-profile",
        "mongodb-rate",
        "mongodb-recommendation",
        "mongodb-reservation",
        "mongodb-user",
    ],
    "request_types": {
        "by_service": [
            ["frontend", "user"],
            ["frontend", "recommendation", "profile"],
            ["frontend", "search", "geo", "rate", "reservation", "profile"],
            ["frontend", "reservation", "user"],
        ],
        "by_all_services": [
            ["frontend", "user", "mongodb-user"],
            [
                "frontend",
                "recommendation",
                "profile",
                "mongodb-recommendation",
                "mongodb-profile",
                "memcached-profile",
            ],
            [
                "frontend",
                "search",
                "geo",
                "rate",
                "reservation",
                "mongodb-geo",
                "memcached-rate",
                "mongodb-rate",
                "mongodb-reservation",
            ],
            [
                "frontend",
                "reservation",
                "user",
                "mongodb-reservation",
                "mongodb-user",
            ],
        ],
        "by_type": ["user", "recommend", "search", "reserve"],
    },
    "frontend_service": "frontend",
}

social_network = {
    "services": [
        "compose-post-service",
        "home-timeline-redis",
        "home-timeline-service",
        "media-frontend",
        "media-memcached",
        "media-mongodb",
        "media-service",
        "nginx-thrift",
        "post-storage-memcached",
        "post-storage-mongodb",
        "post-storage-service",
        "social-graph-mongodb",
        "social-graph-redis",
        "social-graph-service",
        "text-service",
        "unique-id-service",
        "url-shorten-memcached",
        "url-shorten-mongodb",
        "url-shorten-service",
        "user-memcached",
        "user-mention-service",
        "user-mongodb",
        "user-service",
        "user-timeline-mongodb",
        "user-timeline-redis",
        "user-timeline-service",
    ],
    "request_types": {
        "by_service": [
            [
                "nginx-web-server",
                "compose-post-service",
                "text-service",
                "media-service",
                "unique-id-service",
                "user-mention-service",
                "user-service",
                "user-timeline-service",
                "home-timeline-service",
                "post-storage-service",
                "social-graph-service",
                "url-shorten-service",
            ],
            ["nginx-web-server", "home-timeline-service", "post-storage-service"],
            ["nginx-web-server", "user-timeline-service", "post-storage-service"],
        ],
        "by_all_services": [
            [
                "nginx-thrift",
                "compose-post-service",
                "text-service",
                "media-service",
                "unique-id-service",
                "user-mention-service",
                "user-service",
                "user-timeline-service",
                "home-timeline-service",
                "post-storage-service",
                "social-graph-service",
                "url-shorten-service",
                "media-memcached",
                "media-mongodb",
                "user-memcached",
                "user-mongodb",
                "user-timeline-mongodb",
                "user-timeline-redis",
                "home-timeline-redis",
                "post-storage-memcached",
                "post-storage-mongodb",
                "social-graph-mongodb",
                "social-graph-redis",
                "url-shorten-memcached",
                "url-shorten-mongodb",
            ],
            [
                "nginx-thrift",
                "home-timeline-service",
                "post-storage-service",
                "home-timeline-redis",
                "post-storage-memcached",
                "post-storage-mongodb",
            ],
            [
                "nginx-thrift",
                "user-timeline-service",
                "post-storage-service",
                "user-timeline-mongodb",
                "user-timeline-redis",
                "post-storage-memcached",
                "post-storage-mongodb",
            ],
        ],
        "by_type": ["compose_post", "read_home_timeline", "read_user_timeline"],
    },
    "frontend_service": "nginx-thrift",
}
